export const TOOLS_ITEMS = [
  { href: "/intake", label: "Document Evidence" },
  { href: "/jurisdiction", label: "Identify Jurisdiction" },
  { href: "/report-packet", label: "Generate Reports" },
  { href: "/dashboard", label: "Dashboard" },
  { href: "/advocacy", label: "Advocacy Toolkit" },
  { href: "/resources", label: "Resources" },
  { href: "/shelter-tracker", label: "Shelter Accountability" },
  { href: "/stray-tools", label: "Stray & At-Risk" },
  { href: "/usa-map", label: "USA Map" },
  { href: "/authority-directory", label: "Authorities" },
  { href: "/emergency", label: "Emergency" },
  { href: "/foia", label: "FOIA Generator" },
  { href: "/escalation", label: "Escalation Chain" },
  { href: "/witness-statement", label: "Witness Statement" },
  { href: "/state-laws", label: "State Law Guide" },
  { href: "/legislators", label: "Legislative Tracker" },
  { href: "/pattern-detector", label: "Pattern Detector" },
  { href: "/media-contacts", label: "Media Directory" },
  { href: "/agency-tracker", label: "Agency Tracker" },
  { href: "/evidence-vault", label: "Evidence Vault" },
  { href: "/case-summary", label: "Case Summary" },
  { href: "/action-plan", label: "Action Plan" },
  { href: "/heat-emergency", label: "Heat / Cold Emergency" },
  { href: "/national-resources", label: "Resource Directory" },
  { href: "/prosecution-guide", label: "Court & Prosecution" },
  { href: "/my-cases", label: "My Cases" },
  { href: "/surrender-prevention", label: "Surrender Prevention" },
  { href: "/pet-theft", label: "Pet Theft & Recovery" },
  { href: "/hoarding-response", label: "Hoarding Response" },
  { href: "/anonymous-tips", label: "Anonymous Reporting" },
  { href: "/puppy-mill-guide", label: "Puppy Mill Complaints" },
  { href: "/social-campaign", label: "Social Media Campaign" },
  { href: "/vet-abuse-guide", label: "Injury Evidence Guide" },
  { href: "/dogfighting-guide", label: "Dogfighting Response" },
];