import { useState } from "react";
import { Navigation } from "@/components/navigation";
import { AnimatedBackgroundOrbs } from "@/components/animated-orbs";
import { PawPrintScatter } from "@/components/paw-prints";
import { ShieldAlert, AlertTriangle, ChevronDown, ChevronUp, ExternalLink, CheckSquare, Square, Copy, Download, CheckCircle2 } from "lucide-react";

const SIGNS = [
  { category: "Venue Signals", items: ["Aggressive security around a private property", "Unusual night-time traffic or short stays", "Signs of gambling or cash exchanges", "Heavy fencing and hidden access points"] },
  { category: "Animal Signals", items: ["Dogs with repeated injuries", "Animals kept isolated in poor conditions", "Training equipment like treadmills or spring poles", "Young animals used as bait or training animals"] },
  { category: "Crime Signals", items: ["Weapons, narcotics, or stolen property present", "Out-of-state vehicles or short-term visitors", "Coded language about matches or scratches", "Multiple phones or burner numbers"] },
];

const STEPS = [
  { num: "01", title: "Call 911 if fighting is active", body: "Active fights are emergencies and may involve weapons or other crimes." },
  { num: "02", title: "Tip HSUS and local authorities", body: "Use HSUS animal fighting resources and file with animal control or police." },
  { num: "03", title: "Preserve evidence lawfully", body: "Document only from public property. Do not confront suspects." },
  { num: "04", title: "Ask for federal coordination", body: "Mention gambling, weapons, or interstate travel if present." },
];

const CHECKLIST = [
  { id: "a1", text: "Location, date, and time recorded" },
  { id: "a2", text: "Vehicles and plates documented" },
  { id: "a3", text: "Publicly visible photos or video captured" },
  { id: "a4", text: "Police report filed" },
  { id: "a5", text: "HSUS tip submitted" },
  { id: "a6", text: "Evidence stored in VoiceMap Evidence Vault" },
];

type CheckedState = { [k: string]: boolean };

function build(form: { location: string; dateSeen: string; notes: string }): string {
  return `ANIMAL FIGHTING REPORT\nDate: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}\n\nLocation: ${form.location || "[Location]"}\nDate Seen: ${form.dateSeen || "[Date]"}\n\nNotes:\n${form.notes || "[Describe what you observed]"}\n\nGenerated by VoiceMap National Animal Protection Portal`;
}

export default function AnimalFightingGuide() {
  const [open, setOpen] = useState<string | null>(null);
  const [checked, setChecked] = useState<CheckedState>({});
  const [showForm, setShowForm] = useState(false);
  const [copied, setCopied] = useState(false);
  const [form, setForm] = useState({ location: "", dateSeen: new Date().toISOString().split("T")[0], notes: "" });

  const text = build(form);
  const toggle = (id: string) => setChecked((p) => ({ ...p, [id]: !p[id] }));
  const copy = async () => { await navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2500); };
  const download = () => { const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([text], { type: "text/plain" })); a.download = `AnimalFighting_Report_${new Date().toISOString().split("T")[0]}.txt`; a.click(); };

  return (
    <div className="min-h-[100dvh] flex flex-col relative pt-16">
      <AnimatedBackgroundOrbs />
      <Navigation />
      <main className="flex-1 max-w-6xl mx-auto w-full px-4 py-10">
        <div className="mb-6 relative">
          <PawPrintScatter count={5} baseColor="white" />
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-[#c060ff]/35 bg-[#970CDA]/8 text-[#c060ff] text-xs font-black uppercase tracking-widest mb-5"><ShieldAlert className="w-3.5 h-3.5" />Animal Fighting Response</div>
          <h1 className="font-black text-white text-4xl md:text-5xl leading-tight tracking-tight mb-3">Organized Animal Fighting<br /><span className="text-[#47CC5E]">Requires Investigation.</span></h1>
          <p className="text-white/55 text-lg max-w-2xl">A compact reporting guide for suspected animal fighting, with emergency steps, evidence checklist, and a simple complaint generator.</p>
        </div>

        <div className="flex items-start gap-4 px-5 py-4 rounded-2xl bg-white/6 border border-white/18 mb-8"><AlertTriangle className="w-5 h-5 text-white/70 shrink-0 mt-0.5" /><div><p className="text-white font-black text-sm">If fighting is active, call 911 now.</p><p className="text-white/50 text-xs mt-0.5">Do not trespass or confront suspects.</p></div></div>

        <div className="mb-8"><p className="text-white/35 text-xs font-black uppercase tracking-widest mb-4">Warning Signs</p><div className="flex flex-col gap-3">{SIGNS.map((s) => { const isOpen = open === s.category; return (<div key={s.category} className="bg-white/4 border border-white/10 rounded-2xl overflow-hidden"><button className="w-full px-5 py-4 flex items-center justify-between text-left" onClick={() => setOpen(isOpen ? null : s.category)}><p className="text-white font-black text-sm">{s.category}</p>{isOpen ? <ChevronUp className="w-4 h-4 text-white/30" /> : <ChevronDown className="w-4 h-4 text-white/30" />}</button>{isOpen && <div className="border-t border-white/8 px-5 pb-4 pt-3 flex flex-col gap-2">{s.items.map((i) => <div key={i} className="flex gap-2"><div className="w-1.5 h-1.5 rounded-full bg-[#c060ff] shrink-0 mt-1.5" /><p className="text-white/65 text-sm leading-snug">{i}</p></div>)}</div>}</div>); })}</div></div>

        <div className="mb-8"><p className="text-white/35 text-xs font-black uppercase tracking-widest mb-4">How to Report</p><div className="flex flex-col gap-3">{STEPS.map((step) => <div key={step.num} className="flex gap-4 bg-white/4 border border-white/10 rounded-2xl p-4"><div className="w-9 h-9 rounded-xl bg-[#970CDA]/12 border border-[#970CDA]/25 text-[#c060ff] font-black text-sm flex items-center justify-center shrink-0">{step.num}</div><div><p className="text-white font-black text-sm mb-1">{step.title}</p><p className="text-white/55 text-xs leading-relaxed">{step.body}</p></div></div>)}</div></div>

        <div className="bg-white/4 border border-white/10 rounded-2xl p-5 mb-6"><div className="flex items-center justify-between mb-4"><p className="text-white font-black text-sm">Evidence Checklist</p><span className="text-xs font-black text-white/35">{Object.values(checked).filter(Boolean).length}/{CHECKLIST.length}</span></div><div className="grid sm:grid-cols-2 gap-2">{CHECKLIST.map((item) => <button key={item.id} className="flex items-start gap-2.5 text-left p-2.5 rounded-xl hover:bg-white/5 transition-all" onClick={() => toggle(item.id)}>{checked[item.id] ? <CheckSquare className="w-4 h-4 text-[#47CC5E] shrink-0 mt-0.5" /> : <Square className="w-4 h-4 text-white/25 shrink-0 mt-0.5" />}<p className={`text-xs leading-snug ${checked[item.id] ? "text-white/30 line-through" : "text-white/65"}`}>{item.text}</p></button>)}</div></div>

        <div className="bg-white/4 border border-white/10 rounded-2xl overflow-hidden mb-8"><button className="w-full px-5 py-4 flex items-center justify-between text-left" onClick={() => setShowForm((v) => !v)}><div><p className="text-white font-black text-base">Complaint Generator</p><p className="text-white/40 text-sm mt-0.5">Formal report for police and animal control</p></div>{showForm ? <ChevronUp className="w-4 h-4 text-white/40" /> : <ChevronDown className="w-4 h-4 text-white/40" />}</button>{showForm && <div className="border-t border-white/8 px-5 pb-5 pt-4"><div className="grid sm:grid-cols-2 gap-3 mb-4"><div><label className="block text-white/45 text-xs font-black uppercase tracking-widest mb-1.5">Location</label><input type="text" className="w-full bg-white/6 border border-white/12 rounded-xl px-3 py-2.5 text-sm text-white" value={form.location} onChange={(e) => setForm((f) => ({ ...f, location: e.target.value }))} /></div><div><label className="block text-white/45 text-xs font-black uppercase tracking-widest mb-1.5">Date Seen</label><input type="text" className="w-full bg-white/6 border border-white/12 rounded-xl px-3 py-2.5 text-sm text-white" value={form.dateSeen} onChange={(e) => setForm((f) => ({ ...f, dateSeen: e.target.value }))} /></div><div className="sm:col-span-2"><label className="block text-white/45 text-xs font-black uppercase tracking-widest mb-1.5">Notes</label><textarea rows={3} className="w-full bg-white/6 border border-white/12 rounded-xl px-3 py-2.5 text-sm text-white resize-none" value={form.notes} onChange={(e) => setForm((f) => ({ ...f, notes: e.target.value }))} /></div></div><div className="bg-[#0a0f1e] border border-white/10 rounded-xl p-4 font-mono text-xs text-white/55 leading-relaxed whitespace-pre-wrap max-h-52 overflow-y-auto mb-3">{text}</div><div className="flex gap-2"><button onClick={copy} className="flex items-center gap-2 px-5 py-2.5 rounded-full bg-[#47CC5E] text-[#0A1439] font-black text-xs uppercase tracking-wider hover:bg-[#5adb70] transition-all">{copied ? <CheckCircle2 className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}{copied ? "Copied!" : "Copy Report"}</button><button onClick={download} className="flex items-center gap-2 px-5 py-2.5 rounded-full bg-[#970CDA] text-white font-black text-xs uppercase tracking-wider hover:bg-[#aa20ef] transition-all"><Download className="w-3.5 h-3.5" /> Download</button></div></div>}</div>
      </main>
    </div>
  );
}