import { useState, useMemo } from "react";
import { Navigation } from "@/components/navigation";
import { AnimatedBackgroundOrbs } from "@/components/animated-orbs";
import { PawPrintScatter } from "@/components/paw-prints";
import {
  Archive, Camera, FileText, Mail, Mic, Video, Plus, X,
  ChevronDown, ChevronUp, Copy, Download, CheckCircle2,
  Search, Tag, Folder
} from "lucide-react";

const LS_KEY = "voicemap_evidence_vault";
const LS_CONCERNS = "voicemap_concerns";

type EvidenceType =
  | "Photo"
  | "Video"
  | "Audio"
  | "Document"
  | "Correspondence"
  | "Witness Statement"
  | "Receipt / Record"
  | "Other";

interface EvidenceItem {
  id: string;
  caseLabel: string;
  type: EvidenceType;
  title: string;
  description: string;
  dateCapture: string;
  location: string;
  source: string;
  tags: string[];
  chain: string;
  addedAt: string;
}

const TYPE_ICON: Record<EvidenceType, React.ReactNode> = {
  Photo: <Camera className="w-4 h-4" />,
  Video: <Video className="w-4 h-4" />,
  Audio: <Mic className="w-4 h-4" />,
  Document: <FileText className="w-4 h-4" />,
  Correspondence: <Mail className="w-4 h-4" />,
  "Witness Statement": <FileText className="w-4 h-4" />,
  "Receipt / Record": <Archive className="w-4 h-4" />,
  Other: <Tag className="w-4 h-4" />,
};

const TYPE_COLOR: Record<EvidenceType, string> = {
  Photo: "bg-[#47CC5E]/15 text-[#47CC5E] border-[#47CC5E]/30",
  Video: "bg-[#970CDA]/15 text-[#c060ff] border-[#970CDA]/30",
  Audio: "bg-[#970CDA]/10 text-[#c060ff]/80 border-[#970CDA]/20",
  Document: "bg-white/10 text-white/65 border-white/18",
  Correspondence: "bg-[#47CC5E]/10 text-[#47CC5E]/80 border-[#47CC5E]/20",
  "Witness Statement": "bg-white/8 text-white/55 border-white/15",
  "Receipt / Record": "bg-white/6 text-white/45 border-white/12",
  Other: "bg-white/5 text-white/40 border-white/10",
};

const EVIDENCE_TYPES: EvidenceType[] = [
  "Photo", "Video", "Audio", "Document",
  "Correspondence", "Witness Statement", "Receipt / Record", "Other",
];

function loadItems(): EvidenceItem[] {
  try {
    const raw = localStorage.getItem(LS_KEY);
    if (!raw) return [];
    return JSON.parse(raw) as EvidenceItem[];
  } catch { return []; }
}

function saveItems(items: EvidenceItem[]) {
  localStorage.setItem(LS_KEY, JSON.stringify(items));
}

function loadConcernLabels(): string[] {
  try {
    const raw = localStorage.getItem(LS_CONCERNS);
    if (!raw) return [];
    const arr = JSON.parse(raw) as { description?: string }[];
    return arr.map((c, i) => c.description ? c.description.slice(0, 60) : `Concern #${i + 1}`);
  } catch { return []; }
}

function buildChainOfCustody(items: EvidenceItem[]): string {
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const byCase: Record<string, EvidenceItem[]> = {};
  for (const item of items) {
    byCase[item.caseLabel] = [...(byCase[item.caseLabel] ?? []), item];
  }
  return `CHAIN OF CUSTODY / EVIDENCE LOG
Generated: ${today}
Source: VoiceMap National Animal Protection Portal — Evidence Vault

SUMMARY
Total evidence items: ${items.length}
Cases documented: ${Object.keys(byCase).length}
Evidence types: ${[...new Set(items.map((i) => i.type))].join(", ")}

This document serves as a formal evidence log establishing the existence,
description, and provenance of evidence collected in support of documented
animal welfare concerns. This log may be attached to agency complaints,
FOIA requests, legislative letters, or legal proceedings.

${Object.entries(byCase).map(([caseLabel, cs], caseIdx) => `
${"=".repeat(50)}
CASE ${caseIdx + 1}: ${caseLabel}
Items in this case: ${cs.length}
${"=".repeat(50)}

${cs.map((item, idx) => `Item ${idx + 1} — ${item.type.toUpperCase()}
Title: ${item.title}
Description: ${item.description}
Date Captured: ${item.dateCapture}
Location: ${item.location || "Not specified"}
Source / Obtained From: ${item.source || "Reporter's own collection"}
Tags: ${item.tags.length > 0 ? item.tags.join(", ") : "None"}
Chain of Custody Note: ${item.chain || "Captured directly by reporting party"}
Logged to Vault: ${new Date(item.addedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
`).join("\n---\n")}
`).join("")}

LEGAL NOTICE
This evidence log is submitted in good faith. All items described herein are
documented by the reporting party as part of a formal effort to bring alleged
animal welfare concerns to the attention of appropriate authorities. This log
does not constitute a legal determination of any kind. All incidents described
are alleged concerns requiring independent investigation by appropriate authorities.

Generated by VoiceMap National Animal Protection Portal`;
}

const DEMO_ITEMS: EvidenceItem[] = [
  {
    id: "ev1",
    caseLabel: "Multiple dogs chained without water at 123 Oak St",
    type: "Photo",
    title: "3 dogs chained — no water bowls visible",
    description: "Photograph taken from public sidewalk. Three dogs chained with less than 4 feet of movement. No water bowls visible. Extreme heat (98F). Timestamp embedded in EXIF data.",
    dateCapture: "2026-04-14",
    location: "123 Oak St, Houston TX (from public sidewalk)",
    source: "Reporter's own phone camera (iPhone 15)",
    tags: ["neglect", "water", "heat", "chained"],
    chain: "Original file retained on reporter's device. Copy submitted with AC complaint.",
    addedAt: "2026-04-14T15:32:00Z",
  },
  {
    id: "ev2",
    caseLabel: "Multiple dogs chained without water at 123 Oak St",
    type: "Video",
    title: "90-second video — dogs in heat, visible distress",
    description: "Video showing dogs panting heavily. Address spoken aloud at start. No human present during recording. Dogs unable to reach shade. Timestamp in video header.",
    dateCapture: "2026-04-14",
    location: "123 Oak St, Houston TX",
    source: "Reporter's phone (same device as photos)",
    tags: ["video", "distress", "heat", "panting"],
    chain: "Original retained on device. Backup in cloud storage. Submitted to HSUS investigators.",
    addedAt: "2026-04-14T15:35:00Z",
  },
  {
    id: "ev3",
    caseLabel: "Multiple dogs chained without water at 123 Oak St",
    type: "Correspondence",
    title: "Houston AC complaint confirmation email",
    description: "Email confirmation from Houston Animal Control acknowledging receipt of complaint. Case number AC-2026-4421 assigned. Dated April 15, 2026.",
    dateCapture: "2026-04-15",
    location: "N/A (digital)",
    source: "Email from Houston AC automated system",
    tags: ["AC", "case-number", "confirmation"],
    chain: "Printed and saved as PDF. Original in reporter email inbox.",
    addedAt: "2026-04-15T09:12:00Z",
  },
  {
    id: "ev4",
    caseLabel: "Multiple dogs chained without water at 123 Oak St",
    type: "Photo",
    title: "Follow-up visit — conditions unchanged, day 18",
    description: "Second visit to location 18 days after initial report. Same dogs. Same configuration. No change in conditions. No indication of AC visit (no notice posted).",
    dateCapture: "2026-05-02",
    location: "123 Oak St, Houston TX",
    source: "Reporter's own phone",
    tags: ["follow-up", "no-change", "18-days"],
    chain: "Original retained on device. Demonstrates continued neglect and non-response.",
    addedAt: "2026-05-02T11:45:00Z",
  },
  {
    id: "ev5",
    caseLabel: "Unsafe shelter conditions at Riverside County Shelter",
    type: "Document",
    title: "FOIA response — shelter euthanasia records Q1 2026",
    description: "Public records response from Riverside County Animal Services. Contains euthanasia statistics for Q1 2026. Shows 78% euthanasia rate for dogs, significantly above state average.",
    dateCapture: "2026-04-28",
    location: "N/A (public records)",
    source: "Riverside County Animal Services — FOIA response #RC-2026-0412",
    tags: ["FOIA", "euthanasia", "statistics", "shelter"],
    chain: "Original mailed document. Scanned and digitized. Original retained.",
    addedAt: "2026-04-28T14:00:00Z",
  },
  {
    id: "ev6",
    caseLabel: "Unsafe shelter conditions at Riverside County Shelter",
    type: "Witness Statement",
    title: "Statement from former shelter volunteer (name on file)",
    description: "Written statement from volunteer who worked at shelter Jan through March 2026. Describes overcrowding, inadequate medical care, and directives regarding healthy animals. Full name withheld pending review.",
    dateCapture: "2026-04-22",
    location: "Obtained remotely via email",
    source: "Former volunteer (identity known to reporter, withheld from public record)",
    tags: ["witness", "volunteer", "overcrowding"],
    chain: "Statement received via encrypted email. Printed and stored. Original digital file retained.",
    addedAt: "2026-04-22T16:30:00Z",
  },
];

interface AddItemModalProps {
  concerns: string[];
  onSave: (item: EvidenceItem) => void;
  onClose: () => void;
}

function AddItemModal({ concerns, onSave, onClose }: AddItemModalProps) {
  const [form, setForm] = useState({
    caseLabel: concerns[0] ?? "",
    type: "Photo" as EvidenceType,
    title: "",
    description: "",
    dateCapture: new Date().toISOString().split("T")[0],
    location: "",
    source: "",
    tagInput: "",
    tags: [] as string[],
    chain: "",
  });

  const set = <K extends keyof typeof form>(key: K, val: (typeof form)[K]) =>
    setForm((f) => ({ ...f, [key]: val }));

  const addTag = () => {
    const t = form.tagInput.trim().toLowerCase().replace(/\s+/g, "-");
    if (t && !form.tags.includes(t)) set("tags", [...form.tags, t]);
    set("tagInput", "");
  };

  const removeTag = (tag: string) => set("tags", form.tags.filter((t) => t !== tag));

  const canSave = form.title.trim() && form.description.trim() && form.caseLabel;

  const inputCls =
    "w-full bg-white/6 border border-white/12 rounded-xl px-4 py-2.5 text-sm text-white placeholder:text-white/30 focus:outline-none focus:border-[#970CDA]/60 transition-all";

  return (
    <div
      className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-4 bg-black/70 backdrop-blur-sm"
      onClick={onClose}
    >
      <div
        className="w-full max-w-lg bg-[#0c1228] border border-white/12 rounded-3xl overflow-hidden shadow-2xl max-h-[92vh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-6 pt-6 pb-4 border-b border-white/8 shrink-0">
          <div>
            <p className="text-white/40 text-xs font-black uppercase tracking-widest mb-0.5">Evidence Vault</p>
            <p className="text-white font-black text-lg">Log Evidence Item</p>
          </div>
          <button onClick={onClose} className="p-2 rounded-xl text-white/40 hover:text-white hover:bg-white/8 transition-all">
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="flex flex-col gap-4 px-6 py-5 overflow-y-auto">
          <div>
            <label className="block text-white/50 text-xs font-black uppercase tracking-widest mb-1.5">Case / Concern</label>
            {concerns.length > 0 ? (
              <select className={inputCls} value={form.caseLabel} onChange={(e) => set("caseLabel", e.target.value)}>
                {concerns.map((c) => <option key={c}>{c}</option>)}
                <option value="[New Case]">[New Case]</option>
              </select>
            ) : (
              <input className={inputCls} placeholder="Brief case description" value={form.caseLabel} onChange={(e) => set("caseLabel", e.target.value)} />
            )}
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-white/50 text-xs font-black uppercase tracking-widest mb-1.5">Evidence Type</label>
              <select className={inputCls} value={form.type} onChange={(e) => set("type", e.target.value as EvidenceType)}>
                {EVIDENCE_TYPES.map((t) => <option key={t}>{t}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-white/50 text-xs font-black uppercase tracking-widest mb-1.5">Date Captured</label>
              <input type="date" className={inputCls} value={form.dateCapture} onChange={(e) => set("dateCapture", e.target.value)} />
            </div>
          </div>

          <div>
            <label className="block text-white/50 text-xs font-black uppercase tracking-widest mb-1.5">Title</label>
            <input className={inputCls} placeholder="Brief descriptive title" value={form.title} onChange={(e) => set("title", e.target.value)} />
          </div>

          <div>
            <label className="block text-white/50 text-xs font-black uppercase tracking-widest mb-1.5">Description</label>
            <textarea
              rows={4}
              className={inputCls + " resize-none"}
              placeholder="What does this evidence show? How and where was it collected? What makes it relevant?"
              value={form.description}
              onChange={(e) => set("description", e.target.value)}
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-white/50 text-xs font-black uppercase tracking-widest mb-1.5">Location Captured</label>
              <input className={inputCls} placeholder="Address or description" value={form.location} onChange={(e) => set("location", e.target.value)} />
            </div>
            <div>
              <label className="block text-white/50 text-xs font-black uppercase tracking-widest mb-1.5">Source / Origin</label>
              <input className={inputCls} placeholder="e.g. reporter's own phone" value={form.source} onChange={(e) => set("source", e.target.value)} />
            </div>
          </div>

          <div>
            <label className="block text-white/50 text-xs font-black uppercase tracking-widest mb-1.5">Chain of Custody Note</label>
            <input
              className={inputCls}
              placeholder="Where is the original stored? Has it been shared?"
              value={form.chain}
              onChange={(e) => set("chain", e.target.value)}
            />
          </div>

          <div>
            <label className="block text-white/50 text-xs font-black uppercase tracking-widest mb-1.5">Tags</label>
            <div className="flex gap-2">
              <input
                className={inputCls}
                placeholder="Add a tag, press Enter"
                value={form.tagInput}
                onChange={(e) => set("tagInput", e.target.value)}
                onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); addTag(); } }}
              />
              <button
                onClick={addTag}
                className="px-4 py-2.5 rounded-xl bg-white/8 border border-white/12 text-white/60 font-black text-xs hover:bg-white/12 transition-all shrink-0"
              >
                Add
              </button>
            </div>
            {form.tags.length > 0 && (
              <div className="flex flex-wrap gap-1.5 mt-2">
                {form.tags.map((t) => (
                  <span key={t} className="flex items-center gap-1 px-2.5 py-1 rounded-full bg-[#970CDA]/12 text-[#c060ff] border border-[#970CDA]/25 text-xs font-black">
                    {t}
                    <button onClick={() => removeTag(t)} className="hover:text-white transition-colors">
                      <X className="w-2.5 h-2.5" />
                    </button>
                  </span>
                ))}
              </div>
            )}
          </div>

          <div className="flex gap-3 pb-2">
            <button
              disabled={!canSave}
              onClick={() => {
                onSave({
                  id: crypto.randomUUID(),
                  caseLabel: form.caseLabel,
                  type: form.type,
                  title: form.title,
                  description: form.description,
                  dateCapture: form.dateCapture,
                  location: form.location,
                  source: form.source,
                  tags: form.tags,
                  chain: form.chain,
                  addedAt: new Date().toISOString(),
                });
                onClose();
              }}
              className="flex-1 px-5 py-3 rounded-full bg-[#47CC5E] text-[#0A1439] font-black text-xs uppercase tracking-wider hover:bg-[#5adb70] transition-all disabled:opacity-40 disabled:cursor-not-allowed"
            >
              Save to Vault
            </button>
            <button
              onClick={onClose}
              className="px-5 py-3 rounded-full bg-white/6 border border-white/12 text-white/60 font-black text-xs uppercase tracking-wider hover:bg-white/10 transition-all"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function EvidenceCard({ item, onDelete }: { item: EvidenceItem; onDelete: (id: string) => void }) {
  const [expanded, setExpanded] = useState(false);
  return (
    <div className="bg-white/4 border border-white/10 rounded-2xl overflow-hidden hover:border-white/16 transition-all">
      <div className="px-5 py-4">
        <div className="flex items-start gap-3">
          <div className={`w-10 h-10 rounded-xl border flex items-center justify-center shrink-0 ${TYPE_COLOR[item.type]}`}>
            {TYPE_ICON[item.type]}
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap mb-1">
              <span className={`px-2.5 py-0.5 rounded-full text-xs font-black border ${TYPE_COLOR[item.type]}`}>{item.type}</span>
              <span className="text-white/30 text-xs">{item.dateCapture}</span>
            </div>
            <p className="text-white font-bold text-sm leading-snug">{item.title}</p>
            {item.location && <p className="text-white/40 text-xs mt-0.5">{item.location}</p>}
          </div>
          <button
            onClick={() => setExpanded((v) => !v)}
            className="p-1.5 text-white/30 hover:text-white/60 transition-all shrink-0"
          >
            {expanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
          </button>
        </div>

        {expanded && (
          <div className="mt-4 pt-4 border-t border-white/8 space-y-2">
            <p className="text-white/65 text-sm leading-relaxed">{item.description}</p>
            {item.source && (
              <p className="text-white/40 text-xs">
                <span className="text-white/25 font-bold uppercase tracking-wider">Source: </span>{item.source}
              </p>
            )}
            {item.chain && (
              <p className="text-white/40 text-xs">
                <span className="text-white/25 font-bold uppercase tracking-wider">Custody: </span>{item.chain}
              </p>
            )}
            {item.tags.length > 0 && (
              <div className="flex flex-wrap gap-1.5 pt-1">
                {item.tags.map((t) => (
                  <span key={t} className="px-2.5 py-0.5 rounded-full bg-[#970CDA]/8 text-[#c060ff]/60 border border-[#970CDA]/15 text-xs">{t}</span>
                ))}
              </div>
            )}
            <button
              onClick={() => onDelete(item.id)}
              className="mt-2 text-white/25 hover:text-white/50 text-xs font-bold flex items-center gap-1 transition-all"
            >
              <X className="w-3 h-3" /> Remove from vault
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

export default function EvidenceVault() {
  const [items, setItems] = useState<EvidenceItem[]>(loadItems);
  const [useDemo, setUseDemo] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState<EvidenceType | "All">("All");
  const [expandedCase, setExpandedCase] = useState<string | null>(null);
  const [showChain, setShowChain] = useState(false);
  const [copied, setCopied] = useState(false);

  const concernLabels = useMemo(() => loadConcernLabels(), []);
  const activeItems = useDemo ? DEMO_ITEMS : items;

  const filtered = useMemo(() => {
    const q = search.toLowerCase();
    return activeItems.filter((item) => {
      const matchSearch =
        !q ||
        item.title.toLowerCase().includes(q) ||
        item.description.toLowerCase().includes(q) ||
        item.caseLabel.toLowerCase().includes(q) ||
        item.tags.some((t) => t.includes(q));
      const matchType = typeFilter === "All" || item.type === typeFilter;
      return matchSearch && matchType;
    });
  }, [activeItems, search, typeFilter]);

  const byCase = useMemo(() => {
    const map: Record<string, EvidenceItem[]> = {};
    for (const item of filtered) {
      map[item.caseLabel] = [...(map[item.caseLabel] ?? []), item];
    }
    return map;
  }, [filtered]);

  const chainDoc = buildChainOfCustody(activeItems);

  const typeCounts = useMemo(() => {
    const counts: Partial<Record<EvidenceType, number>> = {};
    for (const item of activeItems) counts[item.type] = (counts[item.type] ?? 0) + 1;
    return counts;
  }, [activeItems]);

  const totalCases = useMemo(
    () =>
      Object.keys(
        activeItems.reduce((acc, i) => ({ ...acc, [i.caseLabel]: true }), {} as Record<string, boolean>)
      ).length,
    [activeItems]
  );

  const saveItem = (item: EvidenceItem) => {
    const updated = [...items, item];
    setItems(updated);
    saveItems(updated);
    setUseDemo(false);
  };

  const deleteItem = (id: string) => {
    const updated = items.filter((i) => i.id !== id);
    setItems(updated);
    saveItems(updated);
  };

  const copy = async () => {
    await navigator.clipboard.writeText(chainDoc);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const download = () => {
    const blob = new Blob([chainDoc], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Evidence_Log_${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-[100dvh] flex flex-col relative pt-16">
      <AnimatedBackgroundOrbs />
      <Navigation />
      {showModal && (
        <AddItemModal
          concerns={concernLabels.length > 0 ? concernLabels : ["[Enter case description]"]}
          onSave={saveItem}
          onClose={() => setShowModal(false)}
        />
      )}

      <main className="flex-1 max-w-6xl mx-auto w-full px-4 py-10">
        {/* Header */}
        <div className="mb-8 relative">
          <PawPrintScatter count={5} className="opacity-20" />
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-[#47CC5E]/40 bg-[#47CC5E]/10 text-[#47CC5E] text-xs font-black uppercase tracking-widest mb-5">
            <Archive className="w-3.5 h-3.5" />
            Evidence Vault
          </div>
          <h1 className="font-black text-white text-4xl md:text-5xl leading-tight tracking-tight mb-3">
            Organize Every Piece.<br />
            <span className="text-[#47CC5E]">Build an Unbreakable Case.</span>
          </h1>
          <p className="text-white/55 text-lg max-w-2xl">
            Log, tag, and organize evidence by case — photos, videos, documents, correspondence, witness statements. Generate a formal Chain of Custody document for legal and agency submissions.
          </p>
        </div>

        {/* Stats band */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8">
          {[
            { label: "Total Items", value: activeItems.length, color: "text-white" },
            { label: "Cases", value: totalCases, color: "text-[#47CC5E]" },
            { label: "Photos & Videos", value: (typeCounts.Photo ?? 0) + (typeCounts.Video ?? 0), color: "text-[#c060ff]" },
            { label: "Documents", value: (typeCounts.Document ?? 0) + (typeCounts.Correspondence ?? 0) + (typeCounts["Witness Statement"] ?? 0), color: "text-[#47CC5E]" },
          ].map((s) => (
            <div key={s.label} className="bg-white/4 border border-white/10 rounded-2xl p-4 text-center">
              <div className={`kz-stat-number text-3xl mb-1 ${s.color}`}>{s.value}</div>
              <div className="text-white/40 text-xs font-bold leading-tight">{s.label}</div>
            </div>
          ))}
        </div>

        {/* Controls */}
        <div className="flex items-center justify-between flex-wrap gap-3 mb-4">
          <div className="flex gap-2 flex-wrap">
            <button
              onClick={() => { setShowModal(true); setUseDemo(false); }}
              className="flex items-center gap-2 px-5 py-2.5 rounded-full bg-[#47CC5E] text-[#0A1439] font-black text-xs uppercase tracking-wider hover:bg-[#5adb70] hover:shadow-[0_0_14px_rgba(71,204,94,0.4)] transition-all"
            >
              <Plus className="w-3.5 h-3.5" /> Log Evidence
            </button>
            <button
              onClick={() => setUseDemo((v) => !v)}
              className={`px-4 py-2.5 rounded-full text-xs font-black uppercase tracking-wider border transition-all ${
                useDemo
                  ? "bg-[#970CDA]/20 border-[#970CDA]/40 text-[#c060ff] hover:bg-[#970CDA]/30"
                  : "bg-white/6 border-white/12 text-white/60 hover:bg-white/10"
              }`}
            >
              {useDemo ? "Exit Demo" : "Load Demo Data"}
            </button>
          </div>
          {activeItems.length > 0 && (
            <button
              onClick={() => setShowChain((v) => !v)}
              className="flex items-center gap-2 px-4 py-2.5 rounded-full bg-white/6 border border-white/12 text-white/60 font-black text-xs uppercase tracking-wider hover:bg-white/10 transition-all"
            >
              <FileText className="w-3.5 h-3.5" />
              {showChain ? "Hide" : "View"} Chain of Custody
            </button>
          )}
        </div>

        {/* Search + type filter */}
        {activeItems.length > 0 && (
          <div className="bg-white/3 border border-white/8 rounded-2xl p-4 mb-6 flex flex-col sm:flex-row gap-3">
            <div className="flex-1 relative">
              <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-white/30" />
              <input
                className="w-full bg-white/6 border border-white/12 rounded-xl pl-10 pr-4 py-2.5 text-sm text-white placeholder:text-white/30 focus:outline-none focus:border-[#970CDA]/60 transition-all"
                placeholder="Search by title, description, tag, or case..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
            <div className="flex flex-wrap gap-1.5">
              {(["All", ...EVIDENCE_TYPES] as const).map((t) => (
                <button
                  key={t}
                  onClick={() => setTypeFilter(t)}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-black border transition-all ${
                    typeFilter === t
                      ? "bg-[#970CDA]/20 border-[#970CDA]/40 text-[#c060ff]"
                      : "bg-white/5 border-white/10 text-white/45 hover:text-white hover:bg-white/8"
                  }`}
                >
                  {t !== "All" && TYPE_ICON[t as EvidenceType]}
                  {t === "All" ? "All Types" : t}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Empty state */}
        {activeItems.length === 0 && (
          <div className="text-center py-20 bg-white/3 border border-white/8 rounded-2xl mb-6">
            <Archive className="w-12 h-12 mx-auto mb-4 text-white/20" />
            <p className="text-white/50 font-black text-lg">Your Evidence Vault is empty</p>
            <p className="text-white/30 text-sm mt-2 max-w-sm mx-auto">
              Log every piece of evidence you collect. The vault builds a formal Chain of Custody for legal and agency use.
            </p>
            <div className="flex gap-3 justify-center mt-6">
              <button
                onClick={() => setShowModal(true)}
                className="flex items-center gap-2 px-5 py-2.5 rounded-full bg-[#47CC5E] text-[#0A1439] font-black text-xs uppercase tracking-wider hover:bg-[#5adb70] transition-all"
              >
                <Plus className="w-3.5 h-3.5" /> Log First Item
              </button>
              <button
                onClick={() => setUseDemo(true)}
                className="px-5 py-2.5 rounded-full bg-white/8 border border-white/15 text-white/70 font-black text-xs uppercase tracking-wider hover:bg-white/12 transition-all"
              >
                See Demo
              </button>
            </div>
          </div>
        )}

        {/* Case folders */}
        {Object.entries(byCase).length > 0 && (
          <div className="flex flex-col gap-3 mb-8">
            <p className="text-white/30 text-xs font-black uppercase tracking-widest mb-1">
              {filtered.length} item{filtered.length !== 1 ? "s" : ""} across {Object.keys(byCase).length} case{Object.keys(byCase).length !== 1 ? "s" : ""}
            </p>
            {Object.entries(byCase).map(([caseLabel, cs]) => {
              const isOpen = expandedCase === caseLabel;
              return (
                <div key={caseLabel} className="rounded-2xl border border-white/10 bg-white/3 overflow-hidden">
                  <button
                    className="w-full px-5 py-4 flex items-center gap-4 text-left"
                    onClick={() => setExpandedCase(isOpen ? null : caseLabel)}
                  >
                    <div className="w-9 h-9 rounded-xl bg-[#47CC5E]/12 border border-[#47CC5E]/25 flex items-center justify-center shrink-0">
                      <Folder className="w-4 h-4 text-[#47CC5E]" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-white font-black text-sm leading-snug">{caseLabel}</p>
                      <p className="text-white/40 text-xs mt-0.5">
                        {cs.length} item{cs.length !== 1 ? "s" : ""} · {[...new Set(cs.map((i) => i.type))].join(", ")}
                      </p>
                    </div>
                    {isOpen
                      ? <ChevronUp className="w-4 h-4 text-white/30 shrink-0" />
                      : <ChevronDown className="w-4 h-4 text-white/30 shrink-0" />
                    }
                  </button>

                  {isOpen && (
                    <div className="px-5 pb-5 border-t border-white/8 pt-4 grid md:grid-cols-2 gap-3">
                      {cs
                        .sort((a, b) => a.dateCapture.localeCompare(b.dateCapture))
                        .map((item) => (
                          <EvidenceCard key={item.id} item={item} onDelete={deleteItem} />
                        ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}

        {/* Chain of custody document */}
        {showChain && activeItems.length > 0 && (
          <div className="bg-white/4 border border-white/10 rounded-2xl p-5 mb-8">
            <div className="flex items-center justify-between flex-wrap gap-4 mb-4">
              <div>
                <p className="text-white font-black text-base">Chain of Custody Document</p>
                <p className="text-white/45 text-sm mt-0.5">Formatted for legal proceedings, FOIA attachments, and formal complaints</p>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={copy}
                  className="flex items-center gap-2 px-4 py-2 rounded-full bg-[#47CC5E] text-[#0A1439] font-black text-xs uppercase tracking-wider hover:bg-[#5adb70] transition-all"
                >
                  {copied ? <CheckCircle2 className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? "Copied!" : "Copy"}
                </button>
                <button
                  onClick={download}
                  className="flex items-center gap-2 px-4 py-2 rounded-full bg-[#970CDA] text-white font-black text-xs uppercase tracking-wider hover:bg-[#aa20ef] transition-all"
                >
                  <Download className="w-3.5 h-3.5" /> Download
                </button>
              </div>
            </div>
            <div className="bg-[#0a0f1e] border border-white/10 rounded-xl p-4 font-mono text-xs text-white/65 leading-relaxed whitespace-pre-wrap max-h-72 overflow-y-auto">
              {chainDoc}
            </div>
          </div>
        )}

        {/* Best practices */}
        <div className="bg-white/3 border border-white/8 rounded-2xl p-5">
          <p className="text-white/35 text-xs font-black uppercase tracking-widest mb-4">Evidence best practices</p>
          <div className="grid sm:grid-cols-2 gap-4">
            {[
              { title: "Date and location every item", body: "Every photo and video should have a timestamp. Speak the address aloud at the start of any video recording as an additional record." },
              { title: "Maintain the original", body: "Never alter, crop, or filter evidence photos. Preserve the unedited original. Copies can be made for sharing, but the original is what holds legal weight." },
              { title: "Document provenance", body: "Record where you obtained every piece of evidence — your own device, a FOIA response, a witness email. This establishes authenticity and chain of custody." },
              { title: "Back up in multiple places", body: "Store evidence in at least two separate locations (phone, cloud, external drive). Evidence that exists in only one place is evidence that can be lost." },
              { title: "Witness statements need context", body: "When collecting statements, note the witness's relationship to the case, how you obtained the statement, and whether they consent to being named." },
              { title: "FOIA records are particularly powerful", body: "Documents obtained through public records requests came from the agency itself. Log them here with their reference number for full chain of custody." },
            ].map((tip) => (
              <div key={tip.title} className="flex gap-3">
                <div className="w-1.5 h-1.5 rounded-full bg-[#47CC5E] mt-2 shrink-0" />
                <div>
                  <p className="text-white font-bold text-sm mb-1">{tip.title}</p>
                  <p className="text-white/50 text-xs leading-relaxed">{tip.body}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
