import { AnimatedBackgroundOrbs } from "@/components/animated-orbs";
import { Navigation } from "@/components/navigation";
import { GlassCard } from "@/components/ui/glass-card";
import { GlowButton } from "@/components/ui/glow-button";
import { Printer, Copy, FileText, CheckCircle2 } from "lucide-react";
import { useState } from "react";

export default function ReportPacket() {
  const [copied, setCopied] = useState<string | null>(null);

  const handleCopy = (id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  const emailTemplate = `To Whom It May Concern,

I am writing to formally report an alleged animal welfare concern located at [INSERT LOCATION]. 

Based on my observations on [INSERT DATE], I have documented the following:
[INSERT BRIEF OBJECTIVE DESCRIPTION]

I am requesting that your agency investigate this reported incident in accordance with local ordinances.

Thank you,
[YOUR NAME/ANONYMOUS]`;

  return (
    <div className="min-h-[100dvh] flex flex-col relative pt-16">
      <AnimatedBackgroundOrbs />
      <Navigation />
      
      <div className="fixed bottom-8 right-8 z-50">
        <GlowButton onClick={() => window.print()} className="rounded-full shadow-2xl flex items-center gap-2">
          <Printer className="w-5 h-5" />
          Print / Save PDF
        </GlowButton>
      </div>

      <main className="flex-1 container mx-auto px-4 py-8 max-w-4xl print:max-w-none print:py-0">
        <div className="mb-8 text-center print:text-left print:mb-4">
          <h1 className="text-4xl font-bold text-white print:text-black mb-2">Report Packet</h1>
          <p className="text-white/60 print:text-gray-600">Generated by VoiceMap National Portal</p>
        </div>

        <div className="space-y-6 print:space-y-4">
          <GlassCard className="print:border-gray-200 print:shadow-none print:bg-transparent">
            <h2 className="text-2xl font-semibold text-white print:text-black mb-4 flex items-center gap-2">
              <FileText className="w-6 h-6 text-primary" />
              National Report Summary
            </h2>
            <div className="grid grid-cols-2 gap-4 text-white/80 print:text-black">
              <div>
                <span className="block text-white/50 text-sm">Date Generated</span>
                {new Date().toLocaleDateString()}
              </div>
              <div>
                <span className="block text-white/50 text-sm">Incident ID</span>
                VM-2024-8921
              </div>
              <div className="col-span-2">
                <span className="block text-white/50 text-sm">Status</span>
                Requires Investigation
              </div>
            </div>
          </GlassCard>

          <GlassCard className="print:border-gray-200 print:shadow-none print:bg-transparent">
            <h2 className="text-xl font-semibold text-white print:text-black mb-4">Evidence Checklist</h2>
            <ul className="space-y-3 text-white/80 print:text-black">
              <li className="flex items-center gap-3">
                <CheckCircle2 className="w-5 h-5 text-primary" /> Date & Time documented
              </li>
              <li className="flex items-center gap-3">
                <CheckCircle2 className="w-5 h-5 text-primary" /> Location details provided
              </li>
              <li className="flex items-center gap-3 text-white/40">
                <div className="w-5 h-5 rounded-full border-2 border-white/40" /> Media attached (Pending)
              </li>
            </ul>
          </GlassCard>

          <GlassCard className="print:hidden relative">
            <div className="absolute top-4 right-4">
              <button 
                onClick={() => handleCopy('email', emailTemplate)}
                className="p-2 text-white/60 hover:text-white bg-white/5 hover:bg-white/10 rounded-lg transition-colors"
              >
                {copied === 'email' ? <CheckCircle2 className="w-5 h-5 text-green-400" /> : <Copy className="w-5 h-5" />}
              </button>
            </div>
            <h2 className="text-xl font-semibold text-white mb-4">Suggested Local Report Email</h2>
            <pre className="whitespace-pre-wrap font-sans text-white/70 bg-black/20 p-4 rounded-xl border border-white/5 text-sm">
              {emailTemplate}
            </pre>
          </GlassCard>
        </div>
      </main>
    </div>
  );
}
