import { useState } from "react";
import { Navigation } from "@/components/navigation";
import { AnimatedBackgroundOrbs } from "@/components/animated-orbs";
import { FileSignature, Copy, CheckCircle2, Scale, PenLine, AlertTriangle, Download } from "lucide-react";

const INCIDENT_TYPES = [
  "Neglect",
  "Starvation / dehydration",
  "Physical abuse",
  "Unsafe shelter conditions",
  "Improper euthanasia",
  "Abandonment",
  "Overcrowding",
  "Other reported concern",
];

function buildStatement(form: Record<string, string>) {
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  return `WITNESS STATEMENT

Date: ${today}

I, ${form.name || "[Your full legal name]"}, declare under penalty of perjury that the following is true and correct to the best of my knowledge and direct observation.

1. Witness Information
Name: ${form.name || "[Name]"}
Address: ${form.address || "[Address]"}
Phone: ${form.phone || "[Phone]"}
Email: ${form.email || "[Email]"}

2. Incident Summary
Date / Time Observed: ${form.observedAt || "[Date and time]"}
Location: ${form.location || "[Exact location]"}
Incident Type: ${form.incidentType || "[Select incident type]"}
Animal(s): ${form.animals || "[Animal description]"}

3. Direct Observation
${form.observation || "[Describe exactly what you personally saw, heard, or recorded. Use factual language only. Do not speculate.]"}

4. Evidence Collected
${form.evidence || "[Photos, video, audio, notes, case number, witness names, etc.]"}

5. Additional Context
${form.context || "[Any prior reports, agency non-response, repeated incidents, or contextual details.]"}

6. Requested Action
I request that the appropriate authorities investigate this reported concern immediately and take any actions authorized by law to protect the animals involved.

I affirm that the statements above are true and correct.

Signed: _______________________________
Printed Name: ${form.name || "[Your full legal name]"}
Date: ${today}

---
Generated by VoiceMap National Animal Protection Portal`;
}

export default function WitnessStatement() {
  const [form, setForm] = useState<Record<string, string>>({});
  const [copied, setCopied] = useState(false);
  const [tab, setTab] = useState<"form" | "preview">("form");

  const set = (key: string, value: string) => setForm((prev) => ({ ...prev, [key]: value }));
  const letter = buildStatement(form);

  const copy = async () => {
    await navigator.clipboard.writeText(letter);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    const blob = new Blob([letter], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Witness_Statement_${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const inputCls = "w-full bg-white/6 border border-white/12 rounded-xl px-4 py-2.5 text-sm text-white placeholder:text-white/30 focus:outline-none focus:border-[#970CDA]/60 transition-all";
  const labelCls = "block text-white/50 text-xs font-black uppercase tracking-widest mb-1.5";

  return (
    <div className="min-h-[100dvh] flex flex-col relative pt-16">
      <AnimatedBackgroundOrbs />
      <Navigation />

      <main className="flex-1 max-w-5xl mx-auto w-full px-4 py-10">
        <div className="mb-8">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-[#970CDA]/40 bg-[#970CDA]/10 text-[#c060ff] text-xs font-black uppercase tracking-widest mb-5">
            <FileSignature className="w-3.5 h-3.5" />
            Witness Statement Builder
          </div>
          <h1 className="font-black text-white text-4xl md:text-5xl leading-tight tracking-tight mb-3">
            Turn Your Observation
            <br />
            <span className="text-[#47CC5E]">Into Testimony.</span>
          </h1>
          <p className="text-white/55 text-lg max-w-2xl">
            Generate a clear, factual witness statement you can attach to complaints, reports, or court filings.
          </p>
        </div>

        <div className="flex gap-2 mb-6">
          {(["form", "preview"] as const).map((t) => (
            <button
              key={t}
              onClick={() => setTab(t)}
              className={`px-5 py-2 rounded-full text-xs font-black uppercase tracking-wider transition-all ${tab === t ? "bg-[#970CDA] text-white" : "bg-white/6 text-white/50 border border-white/10 hover:bg-white/10"}`}
            >
              {t === "form" ? "Build Statement" : "Preview Statement"}
            </button>
          ))}
        </div>

        {tab === "form" && (
          <div className="flex flex-col gap-6">
            <div className="bg-white/4 border border-white/10 rounded-2xl p-6">
              <p className="text-white font-black text-base mb-5">Witness Information</p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="sm:col-span-2">
                  <label className={labelCls}>Full Legal Name *</label>
                  <input className={inputCls} value={form.name ?? ""} onChange={(e) => set("name", e.target.value)} />
                </div>
                <div>
                  <label className={labelCls}>Phone</label>
                  <input className={inputCls} value={form.phone ?? ""} onChange={(e) => set("phone", e.target.value)} />
                </div>
                <div>
                  <label className={labelCls}>Email</label>
                  <input className={inputCls} value={form.email ?? ""} onChange={(e) => set("email", e.target.value)} />
                </div>
                <div className="sm:col-span-2">
                  <label className={labelCls}>Address</label>
                  <input className={inputCls} value={form.address ?? ""} onChange={(e) => set("address", e.target.value)} />
                </div>
              </div>
            </div>

            <div className="bg-white/4 border border-white/10 rounded-2xl p-6">
              <p className="text-white font-black text-base mb-5">Incident Details</p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className={labelCls}>Observed At</label>
                  <input className={inputCls} placeholder="Date and time" value={form.observedAt ?? ""} onChange={(e) => set("observedAt", e.target.value)} />
                </div>
                <div>
                  <label className={labelCls}>Incident Type</label>
                  <select className={inputCls} value={form.incidentType ?? ""} onChange={(e) => set("incidentType", e.target.value)}>
                    <option value="">Select type</option>
                    {INCIDENT_TYPES.map((t) => <option key={t} value={t}>{t}</option>)}
                  </select>
                </div>
                <div className="sm:col-span-2">
                  <label className={labelCls}>Location</label>
                  <input className={inputCls} placeholder="Exact address or description" value={form.location ?? ""} onChange={(e) => set("location", e.target.value)} />
                </div>
                <div className="sm:col-span-2">
                  <label className={labelCls}>Animal(s)</label>
                  <input className={inputCls} placeholder="Species, number, identifiers" value={form.animals ?? ""} onChange={(e) => set("animals", e.target.value)} />
                </div>
                <div className="sm:col-span-2">
                  <label className={labelCls}>Direct Observation *</label>
                  <textarea className={`${inputCls} resize-none h-28`} placeholder="Describe exactly what you personally observed." value={form.observation ?? ""} onChange={(e) => set("observation", e.target.value)} />
                </div>
                <div className="sm:col-span-2">
                  <label className={labelCls}>Evidence Collected</label>
                  <textarea className={`${inputCls} resize-none h-20`} placeholder="Photos, videos, case numbers, witness names" value={form.evidence ?? ""} onChange={(e) => set("evidence", e.target.value)} />
                </div>
                <div className="sm:col-span-2">
                  <label className={labelCls}>Additional Context</label>
                  <textarea className={`${inputCls} resize-none h-20`} placeholder="Prior complaints, agency non-response, pattern of concern" value={form.context ?? ""} onChange={(e) => set("context", e.target.value)} />
                </div>
              </div>
            </div>

            <button onClick={() => setTab("preview")} className="w-full px-6 py-4 rounded-full bg-[#970CDA] text-white font-black text-sm uppercase tracking-wider hover:bg-[#aa20ef] transition-all flex items-center justify-center gap-2">
              <PenLine className="w-4 h-4" /> Preview & Export
            </button>
          </div>
        )}

        {tab === "preview" && (
          <div>
            <div className="flex gap-3 mb-4">
              <button onClick={copy} className="flex items-center gap-2 px-5 py-2.5 rounded-full bg-[#47CC5E] text-[#0A1439] font-black text-xs uppercase tracking-wider hover:bg-[#5adb70] transition-all">
                {copied ? <CheckCircle2 className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? "Copied!" : "Copy to Clipboard"}
              </button>
              <button onClick={download} className="flex items-center gap-2 px-5 py-2.5 rounded-full bg-[#970CDA] text-white font-black text-xs uppercase tracking-wider hover:bg-[#aa20ef] transition-all">
                <Download className="w-4 h-4" /> Download .txt
              </button>
              <button onClick={() => setTab("form")} className="flex items-center gap-2 px-5 py-2.5 rounded-full bg-white/8 text-white/60 border border-white/12 font-bold text-xs hover:bg-white/14 transition-all">
                Edit
              </button>
            </div>
            <div className="bg-[#0a0f1e] border border-white/12 rounded-2xl p-6 font-mono text-xs text-white/75 leading-relaxed whitespace-pre-wrap overflow-x-auto">
              {letter}
            </div>
            <div className="mt-4 flex items-start gap-3 px-5 py-4 rounded-xl bg-[#47CC5E]/10 border border-[#47CC5E]/25">
              <Scale className="w-5 h-5 text-[#47CC5E] shrink-0 mt-0.5" />
              <p className="text-white/70 text-sm leading-relaxed">
                Use factual, first-hand observations only. Do not speculate or accuse beyond what you directly observed.
              </p>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
